name: focus_backend
description: Backend do Daily XP 
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  postgres: ^2.6.2
  dotenv: ^4.1.0

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.26.3
